### ISSUE TITLE
Mount empty

### ISSUE THREAD

**Issue by dreher-in** [devdetour/TelegramFUSE#3]
Hi,

first of all thank you. I am currently trying to get it up but I am stuck and need some help to debug it further.

OS: Ubuntu 22.04
Python: Python3.10
Fuse: libfuse3-3

.env is proparly set with my App details. Telegram Channel link is for example https://t.me/cKure

```
~/TelegramFUSE/Telegram$ python3 main.py mount/
USING ENCRYPTION:  False

```

That's all I see after running it.

```
tail -f example.log 
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 7333236048030067348 to ResolveUsernameRequest (7f5b2699c6a0)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 32 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.extensions.messagepacker:Assigned msg_id = 7333236048031886956 to MsgsAck (7f5b2694fee0)
DEBUG:telethon.network.mtprotosender:Encrypting 1 message(s) in 36 bytes for sending
DEBUG:telethon.network.mtprotosender:Encrypted messages put in a queue to be sent
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Handling RPC result for message 7333236048030067348
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
```

That's all, any idea?

Thanks in advanced.

**Comment by devdetour** [comment]
Hi, can you share some more details? Sounds like this issue happens trying to upload a file - how large is the file? Very large files may take a long time.

To check that it is working, you can try uploading and downloading a small text file.

If you're trying to read messages from an existing channel with this program (that you haven't uploaded yourself) - this won't work. This program is only aware of content you upload and download yourself through the program.

**Comment by dreher-in** [comment]
Thanks for your answer. I was not aware of the restriction that only uploaded content is available. Then it makes sense that my mount point is empty.
